### ISSUE TITLE
CSS / design review

### ISSUE THREAD

**Issue by aaronfraint** [dvrpc/sidewalk-data-viz#3]
The webmap's UI is based upon the [Bootstrap "dashboard" example](https://getbootstrap.com/docs/4.0/examples/dashboard/), which gives you a sticky navbar on top and sidebar to the left. 

- It looks good full-screen on a monitor, but on a 13" laptop it's scrunched and as it gets smaller the sidebar disappears. Should we figure out a way to display this on mobile, or just optimize for desktop?

- We could also use a general review of the HTML and CSS files. I suspect some of the divs have too many classes that aren't really helping us here. 

- And finally, are there any visual changes that would make it look nicer and/or easier to use?

**Comment by mmolta** [comment]
A couple notes:

- Add media queries to change to a single column layout at the right breakpoint(s) and this will allow the map to be viewable on narrow and mobile devices. Check out any of the [TIP](www.dvrpc.org/TIP/PA/), [RTSP](www.dvrpc.org/webmaps/RTSP/), [Crash Data](www.dvrpc.org/review/crash-data/) on your phone for example layouts. 
- We'll revisit the HTML/CSS when this goes through official review. Two quick things from glancing at the `index.html` file would be to fill out the `<meta>` tags (keywords, OG tags, GA script, etc) and since you're using two `<nav>` elements, use `aria-label` to make them distinguishable by role for screen readers. Also the header hierarchy (going from h2 to h6) should be updated. 
- will also revisit visual changes on formal review. 
- good use of semantic HTML otherwise
